title: ğŸ‘¨â€ğŸ’» LaurentFTech
description: "Home"
theme: minima
author: "Laurent FRANCOISE"

theme: minima

# Minima social links
github_username: laurentftech

# Minima: show excerpts in the frontpage
show_excerpts: true

header_pages:
    - index.md
    - _pages/podcast_generator.md

include:
    - _pages

plugins:
    - jekyll-redirect-from

