title: ğŸ‘¨â€ğŸ’» LaurentFTech
description: "LaurentFTech web site"
theme: minima

# Navigation
nav:
  - title: Presentation
    url: /
  - title: Podcast Generator
    url: https://laurentftech.github.io/Podcast_generator